# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/combXDC.xdc

# Block Designs: bd/BlkTest/BlkTest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkTest || ORIG_REF_NAME==BlkTest} -quiet] -quiet

# IP: bd/BlkTest/ip/BlkTest_imageDisplay_0_0/BlkTest_imageDisplay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkTest_imageDisplay_0_0 || ORIG_REF_NAME==BlkTest_imageDisplay_0_0} -quiet] -quiet

# IP: bd/BlkTest/ip/BlkTest_UARTBRAMInterface_0_0/BlkTest_UARTBRAMInterface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkTest_UARTBRAMInterface_0_0 || ORIG_REF_NAME==BlkTest_UARTBRAMInterface_0_0} -quiet] -quiet

# IP: bd/BlkTest/ip/BlkTest_blk_mem_gen_0_0/BlkTest_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BlkTest_blk_mem_gen_0_0 || ORIG_REF_NAME==BlkTest_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/BlkTest/BlkTest_ooc.xdc
